# Project information
site_name: Product Documentation
site_description: Placeholder for  Docs
site_author: n/a

# Page tree
nav:
  - Home: index.md
  - User Guide:
    - Welcome Page: page1.md
    - page 2: page2.md
    - page 3: page3.md

# Configuration
theme: readthedocs

# Favicon to be rendered
#favicon: valtix-favico.ico

# Copyright
copyright: 'Copyright &copy; 2020 CN'
