# Project information
site_name: Product Documentation
site_description: Placeholder for  Docs
site_author: n/a

# Page tree
nav:
- Home: index.md
- Setup Guides:
  - AWS Setup Guide:
    - Overview: page1.md
    - Onboarding: page1.md
    - Preparing Your Account: page1.md
    - Enabling CloudTrail: page1.md
    - Enabling VPC flow logs: page1.md
  - Azure Setup Guide:
    - Overview: page1.md
    - Preparing Your Deployment: page1.md
    - Registering the Valtix Settings: page1.md
    - Setting Up Your Azure Gateway: page1.md
- User Guide:
  - Dashboard:
    - Dashboard:
      - Understanding the Dashboard: page1.md
  - Investigate:
    - System Status:
      - Audit Logs: page1.md
      - System Logs: page1.md
    - Flow Analytics:
      - All Events: page1.md
      - Flow Logs: page1.md
      - Firewall Events: page1.md
      - Network Threats: page1.md
      - Web Attacks: page1.md
      - HTTPS Logs: page1.md
      - Reports: page1.md
    - Network Analytics:
      - Stats: page1.md
  - Manage:
    - Security Policies:
      - Rules: page1.md
      - Addresses: page1.md
      - DNS Records: page1.md
      - Services: page1.md
      - Certificates: page1.md
    - Profiles:
      - Decryption: page1.md
      - Network Intrusion: page1.md
      - Web Protection: page1.md
      - Malicious Sources: page1.md
      - Packet Capture: page1.md
      - Log Forwarding: page1.md
      - Diagnostics: page1.md
      - DNS: page1.md
    - Cloud Accounts:
      - Accounts: page1.md
      - Inventory: page1.md
    - Gateways:
      - Gateways:
        - Overview: page1.md
        - Viewing gateways: page1.md
        - Adding gateways: page1.md
    - VPN:
      - VPN Gateways: page1.md
      - Customer Gateways: page1.md
      - VPN Connections: page1.md
  - Settings:
    - Management:
      - Users: page1.md
      - Roles: page1.md
      - Account: page1.md
      - System: page1.md
    - Alert Profiles:
      - Services: page1.md
      - Alert: page1.md
- Features:
      - Alerting: page1.md
      - Syslog Forwarding: page1.md
        
# Configuration
theme: readthedocs
extra_css:
    - css/extra.css

# Copyright
copyright: 'Copyright &copy; 2020 CN'

plugins:
    - search
