# Project information
site_name: Product Documentation
site_description: Placeholder for  Docs
site_author: n/a

# Page tree
nav:
- Home: index.md
- Guide 1: 
  - Welcome Page: page1.md
  - page 2: page2.md
  - page 3: page3.md
- Guide 2:
  - G2P1: page1.md
  - G2p2: page2.md
  - G2p3: page3.md
        
# Configuration
theme: readthedocs
extra_css:
    - css/extra.css
    - css/theme_extra.css

# Copyright
copyright: 'Copyright &copy; 2020 CN'

plugins:
    - search
